[package]
name = "core-data"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm = { version = "1", features = ["runtime-tokio-rustls", "sqlx-postgres"] }
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
