[package]
name = "core-data-migration"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "core_data_migration"
path = "src/lib.rs"

[dependencies]
sea-orm-migration = { version = "1", features = ["runtime-tokio-rustls", "sqlx-postgres"] }
